#Installation of OS-Nova 
---

  - name: Installing Nova
    apt:
      name: nova-compute
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Configuring nova.conf files
    tags: nova, edit, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "transport_url = rabbit://"
      line: "transport_url == rabbit://openstack:0uma999@controller"
      state: present

  - name: Configuring Identity User Services (auth_strategy)
    lineinfile:
      path: /etc/nova/nova.conf
      line: "auth_strategy = keystone"
      state: present
    check_mode: yes

  - name: Configuring the file of keystone_authtoken
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "www_authenticate_uri = <None>"
      line: "www_authenticate_uri = http://controller:5000"
      state: present

  - name: Configuring the file of keystone_authtoken (Memcached) pt. 1
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "memcached_servers = <None>"
      line: "memcached_servers = controller:11211"
      state: present

  - name: Configuring the file of keystone_authtoken pt. 2
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "auth_type = <None>"
      line: "auth_type = password"
      state: present

  - name: Adding the configuration file for authtoken
    lineinfile:
      path: /etc/nova/nova.conf
      insertafter: '^\[keystone_authtoken\]'
      line: "auth_url = http://controller:5000"
      state: present


  - name: Adding the configuration file for authtoken pt. 1
    lineinfile:
      dest: /etc/nova/nova.conf
      insertafter: '^\[keystone_authtoken\]'
      line: "project_domain_name = Default"
      state: present

  - name: Adding the configuration file for authtoken pt. 2
    lineinfile:
      path: /etc/nova/nova.conf
      insertafter: '^\[keystone_authtoken\]'
      line: "user_domain_name = Default"
      state: present

  - name: Adding the configuration file for authtoken pt. 3
    lineinfile:
      path: /etc/nova/nova.conf
      insertafter: '^\[keystone_authtoken\]'
      line: "project_name = service"
      state: present

  - name: Adding the configuration file for authtoken pt. 4 (Username)
    lineinfile:
      path: /etc/nova/nova.conf
      insertafter: '^\[keystone_authtoken\]'
      line: "username = admin"
      state: present

  - name: Adding the configuration file for authtoken pt. 5 (password)
    lineinfile:
      path: /etc/nova/nova.conf
      insertafter: '^\[keystone_authtoken\]'
      line: "password = 0uma999"
      state: present

  - name: Configuring the nova.conf remote console access (vnc) for neutron section (IP)
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "my_ip = <host_ipv4>"
      line: "my_ip = 192.168.56.116"
      state: present

  - name: Configuring the nova.conf remote console access (vnc) for neutron section (IP) pt. 1
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "auth_url = <None>"
      line: "auth_url = http://controller:5000"
      state: present

  - name: Configuring the nova.conf remote console access (authoken) for neutron section
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "auth_type = <None>"
      line: "auth_type = password"
      state: present

  - name: Configuring the nova.conf remote console access (authoken)  for neutron section pt. 2
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "project_domain_name = <None>"
      line: "project_domain_name = default"
      state: present

  - name: Configuring the nova.conf remote console access (authoken)  for neutron section pt. 3
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "user_domain_name = <None>"
      line: "user_domain_name = default"
      state: present

  - name: Configuring the nova.conf remote console access (authoken)  for neutron section pt. 4
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "region_name = <None>"
      line: "region_name = RegionOne"
      state: present

  - name: Configuring the nova.conf remote console access (authoken) for neutron section pt. 5
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "project__name = <None>"
      line: "project_name = service"
      state: present

  - name: Configuring the nova.conf remote console access (authoken) for neutron section pt. 6
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "username = <None>"
      line: "username = neutron"
      state: present

  - name: Configuring the nova.conf remote console access (authoken) for neutron section pt. 7
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "password = <None>"
      line: "password = 0uma666"
      state: present

  - name: Configuring the nova.conf remote console access (vnc) for neutron section pt. 1
    lineinfile:
      path: /etc/nova/nova.conf
      line: "enabled = true"
      state: present
    check_mode: yes

  - name: Configuring the nova.conf remote console access (vnc) for neutron section pt. 2
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "server_listen = 127.0.0.1"
      line: "server_listen = 0.0.0.0"
      state: present

  - name: Configuring the nova.conf remote console access (vnc) for neutron section pt. 3
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "server_proxyclient_address = 127.0.0.1"
      line: "server_proxyclient_address = $my_ip"
      state: present

  - name: Configuring the nova.conf remote console access (vnc) for neutron section pt. 4
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "novncproxy_base_url = http://127.0.0.1:6080/vnc_auto.html"
      line: "novncproxy_base_url = http://controller:6080/vnc_auto.html"
      state: present

  - name: Configuring the nova.conf remote console access (glance) for neutron section
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "api_servers = <None>"
      line: "api_servers = http://controller:9292"
      state: present

  - name: Configuring the nova.conf remote console access (oslo_concurrency) for neutron section
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "lock_path = <None>"
      line: "lock_path = /var/lib/nova/tmp"
      state: present

  - name: Configuring the nova.conf remote console access (placement) for neutron section
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "auth_url = <None>"
      line: "auth_url = http://controller:5000"
      state: present

  - name: Configuring the nova.conf remote console access (placement) for neutron section pt. 2
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "auth_type = <None>"
      line: "auth_type = password"
      state: present

  - name: Configuring the nova.conf remote console access (placement) for neutron section pt. 3
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "project_domain_name = <None>"
      line: "project_domain_name = Default"
      state: present

  - name: Configuring the nova.conf remote console access (placement) for neutron section pt. 4
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "user_domain_name = <None>"
      line: "user_domain_name = Default"
      state: present

  - name: Configuring the nova.conf remote console access (placement) for neutron section pt. 5
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "region_name = <None>"
      line: "region_name = RegionOne"
      state: present

  - name: Configuring the nova.conf remote console access (placement) for neutron section pt. 6
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "project__name = <None>"
      line: "project_name = service"
      state: present

  - name: Configuring the nova.conf remote console access (placement) for neutron section pt. 7
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "username = <None>"
      line: "username = placement"
      state: present

  - name: Configuring the nova.conf remote console access (placement) for neutron section pt. 8
    tags: nova, ubuntu
    lineinfile:
      path: /etc/nova/nova.conf
      regexp: "password = <None>"
      line: "password = 0uma999"
      state: present

  - name: Restarting the Nova service
    service:
      name: nova-compute
      state: restarted

